baseURL = "https://workerpedia.co"
languageCode = "en-us"
title = "Workerpedia"
theme = "learn"
publishdir = "docs"

[params]
disableNextPrev = true
themeVariant = "red"
custom_css = [ "custom.css" ]

[outputs]
home = [ "HTML", "RSS", "JSON"]
