baseURL = "https://idc-snoe.github.io/idc-answers/"
languageCode = "en-us"
title = "Leftpedia"
theme = "learn"
publishdir = "docs"
[params]
disableAssetsBusting = true
themeVariant = "red"
[outputs]
home = [ "HTML", "RSS", "JSON"]
