backend:
  name: github
  repo: "the-idc/workerpedia"
  branch: master
  api_root: "https://api.github.com"
  base_url: "https://api.netlify.com"
  auth_endpoint: auth
  open_authoring: true
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "claims"
    label: "Claim"
    folder: "content/claims"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Source", name: "source", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
